# Generated by Django 5.2.1 on 2025-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lookup_time', models.DateTimeField()),
            ],
        ),
    ]
